# Generated by Django 3.1.2 on 2021-03-01 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_management_app', '0007_auto_20210301_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('given_date', models.DateField()),
                ('due_date', models.DateField()),
                ('fee_amount', models.FloatField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_management_app.courses')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_management_app.students')),
            ],
        ),
    ]
